import {useEffect,useState,type FormEvent} from 'react'
import {api,type Cedente,type Recebivel,type Resultado,type Liquidacao} from './services/api'
import './styles.css'
const M=['BRL','USD'], T=['DUPLICATA','CHEQUE']
const money=(v:number|undefined,c='BRL')=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(v)
function ResultadoView({r}:{r:Resultado}){return <div className="resultado"><b>Resultado da operação</b><p>Valor presente <strong>{money(r.valorPresente,r.moedaPagamento)}</strong></p><p>Deságio <strong>{money(r.valorDesagio,r.moedaPagamento)}</strong></p><p>Prazo <strong>{r.prazoMeses} meses</strong></p><p>Spread <strong>{r.spread}%</strong></p><p>Taxa base <strong>{r.taxaBase}%</strong></p>{r.taxaCambioUtilizada!=null&&<p>Taxa de câmbio <strong>{r.taxaCambioUtilizada}</strong></p>}<p className="total">Valor final <strong>{money(r.valorFinal,r.moedaPagamento)}</strong></p></div>}
function App(){
 const [cedentes,setCedentes]=useState<Cedente[]>([]),[recebiveis,setRecebiveis]=useState<Recebivel[]>([]),[resultado,setResultado]=useState<Resultado|null>(null),[extrato,setExtrato]=useState<Liquidacao[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState('')
 const load=async()=>{const [c,r]=await Promise.all([api.cedentes(),api.recebiveis()]);setCedentes(c);setRecebiveis(r)}
 useEffect(()=>{void load().catch(e=>setMsg(e.message))},[])
 const submit=(name:string,fn:()=>Promise<void>)=>async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(name);setMsg('');try{await fn()}catch(e){setMsg(e instanceof Error?e.message:'Erro ao processar solicitação.')}finally{setBusy('')}}
 const field=(name:string,label:string,type='text')=><label>{label}<input required name={name} type={type}/></label>
 return <main><header><div><small>SRM</small><h1>Credit Engine</h1></div><span>Recebíveis, câmbio e liquidação</span></header>{msg&&<div className="alert">{msg}</div>}
 <section><h2>Simulação de recebível</h2><form onSubmit={submit('simular',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);setResultado(await api.simular({valorFace:Number(f.get('valorFace')),dataVencimento:f.get('dataVencimento'),tipo:f.get('tipo'),moedaPagamento:f.get('moedaPagamento')}))})}>{field('valorFace','Valor de face','number')}{field('dataVencimento','Data de vencimento','date')}<label>Tipo<select name="tipo">{T.map(x=><option key={x}>{x}</option>)}</select></label><label>Moeda de pagamento<select name="moedaPagamento">{M.map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy==='simular'}>{busy==='simular'?'Simulando…':'Simular'}</button></form>{resultado&&<ResultadoView r={resultado}/>}</section>
 <div className="cols"><section><h2>Cadastro de cedente</h2><form onSubmit={submit('cedente',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);await api.cedente({nome:String(f.get('nome')),documento:String(f.get('documento'))});await load();setMsg('Cedente cadastrado.')})}>{field('nome','Nome')}{field('documento','Documento')}<button disabled={busy==='cedente'}>Cadastrar cedente</button></form></section><section><h2>Cadastro de taxa de câmbio</h2><form onSubmit={submit('cambio',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);await api.cambio({moedaOrigem:String(f.get('moedaOrigem')),moedaDestino:String(f.get('moedaDestino')),taxa:Number(f.get('taxa')),vigenteEm:new Date(String(f.get('vigenteEm'))).toISOString()});setMsg('Taxa de câmbio cadastrada.')})}><label>Origem<select name="moedaOrigem">{M.map(x=><option key={x}>{x}</option>)}</select></label><label>Destino<select name="moedaDestino">{M.map(x=><option key={x}>{x}</option>)}</select></label>{field('taxa','Taxa','number')}{field('vigenteEm','Vigente em','datetime-local')}<button disabled={busy==='cambio'}>Cadastrar taxa</button></form></section></div>
 <section><h2>Cadastro de recebível</h2><form onSubmit={submit('recebivel',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);await api.recebivel({cedenteId:String(f.get('cedenteId')),tipo:String(f.get('tipo')),valorFace:Number(f.get('valorFace')),dataVencimento:String(f.get('dataVencimento'))});await load();setMsg('Recebível cadastrado.')})}><label>Cedente<select required name="cedenteId"><option value="">Selecione</option>{cedentes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Tipo<select name="tipo">{T.map(x=><option key={x}>{x}</option>)}</select></label>{field('valorFace','Valor de face','number')}{field('dataVencimento','Data de vencimento','date')}<button disabled={busy==='recebivel'}>Cadastrar recebível</button></form></section>
 <section><h2>Liquidação</h2><form onSubmit={submit('liquidar',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);setResultado(await api.liquidar(String(f.get('recebivelId')),String(f.get('moedaPagamento'))));await load();setMsg('Recebível liquidado.')})}><label>Recebível<select required name="recebivelId"><option value="">Selecione</option>{recebiveis.filter(r=>r.status==='PENDENTE').map(r=><option key={r.id} value={r.id}>{r.tipo} · {money(r.valorFace)} · {r.dataVencimento}</option>)}</select></label><label>Moeda de pagamento<select name="moedaPagamento">{M.map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy==='liquidar'}>{busy==='liquidar'?'Liquidando…':'Liquidar'}</button></form>{resultado&&<ResultadoView r={resultado}/>}</section>
 <section><h2>Extrato de liquidações</h2><form onSubmit={submit('extrato',async()=>{const f=new FormData(event!.currentTarget as HTMLFormElement);setExtrato(await api.liquidacoes({dataInicio:String(f.get('dataInicio')||''),dataFim:String(f.get('dataFim')||''),cedenteId:String(f.get('cedenteId')||''),moedaPagamento:String(f.get('moedaPagamento')||'')}))})}>{field('dataInicio','Data inicial','date')}{field('dataFim','Data final','date')}<label>Cedente<select name="cedenteId"><option value="">Todos</option>{cedentes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Moeda<select name="moedaPagamento"><option value="">Todas</option>{M.map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy==='extrato'}>Filtrar</button></form>{extrato.length>0&&<table><thead><tr><th>Data</th><th>Recebível</th><th>Moeda</th><th>Valor final</th></tr></thead><tbody>{extrato.map(x=><tr key={x.id}><td>{new Date(x.liquidadoEm).toLocaleString('pt-BR')}</td><td>{x.recebivelId}</td><td>{x.moedaPagamento}</td><td>{money(x.valorFinal,x.moedaPagamento)}</td></tr>)}</tbody></table>}</section></main>
}
export default App
